export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  CONSOLIDATED = 'CONSOLIDATED',
  DISPATCHED = 'DISPATCHED',
  IN_TRANSIT = 'IN_TRANSIT',
  DELIVERED = 'DELIVERED',
  SETTLEMENT_ELIGIBLE = 'SETTLEMENT_ELIGIBLE',
  CANCELLED = 'CANCELLED',
}
